### ISSUE TITLE
スクリーンネームを変更すると残高が失われる

### ISSUE THREAD

**Issue by mogamin314** [namuyan/nem-tip-bot-bug-report#1]
日時:2017/08/30 18時
[変更前](https://twitter.com/Nagemona1/status/902826579792871425)
この時点で100xemとモザイクが入っていましたが、スクリーンネームを@ testtesttrtttに変更し残高確認すると
[変更後](https://twitter.com/Nagemona1/status/902834189422149632)
> Error10:You don't have account info. It's a new account.

と残高が消失しています。

**Comment by mogamin314** [comment]
Twitter:https://twitter.com/Nagemona
NEM:@ kancolle

**Comment by namuyan** [comment]
バグ報告有難うございます。
tipbot内部ではスクリーンネームとTagを直接結びつけていました。
ユーザーの意思がなければ変更できない事から放置しておりました。
しかし公式から容易に変更できることからアカウント情報が追従しないと面倒な事になりますね。
このプルリクをバグと認め100XEM送ろうと思います。
有難うございました。
