### ISSUE TITLE
モザイクの徴収機能を利用して他の利用者からxemを徴収する

### ISSUE THREAD

**Issue by ocknamo** [namuyan/nem-tip-bot-bug-report#2]
方法（自分で出金する際の手数料はdeposit分しか使用できないことがわかりましたので修正しました）
1. "徴収料コンスタント（定額）: 900.000000 nem:xem"などの高額でかつ定額手数料のmosaicを作成。
2. tipnemのアドレスになるべく大量に入金する。手数料は900xemかかる。
3. tipnem tip で大量に配布を行う。
4. 出金を誘導し集金する。2人以上出金したら成功。

実施例：
トランザクションハッシュ
入金
73f3de50c3cf86968d130c4747a07fed41e13aa66836f954bca45956f53a506b
出金
27d793cb8cd38ca3d7e2b76028bce1dc6cc6c2ac624dd7d95b12cef59f540e7e
tipで配布されたアカウントが出金した場合
5b75364324b46aa1d071197f9b8a13f2ef6f1b3c1b3e79d03d8b3b3ff3505329

**Comment by namuyan** [comment]
バグ報告有難うございます。
> 出金を誘導し集金する
とありますが、これは別の人に高額Levy付きMosaicを与え、それを出金させることでLevy経由でXEMを得るという事でしょうか？

**Comment by ocknamo** [comment]
そういう意味です。tip自体には手数料がかかりませんので、ノーコストで沢山の人に拡散することが可能です。

2017/08/31 午後3:36 "namuyan" <notifications@github.com>:

**Comment by namuyan** [comment]
これは利用者の問題なのでバグとは認めがたいです。
申し訳ありませんが基準に即しませんのでCloseさせてもらいます。

**Comment by ocknamo** [comment]
了解です。

2017/09/01 午前11:03 "namuyan" <notifications@github.com>:
