### ISSUE TITLE
残高が減らず出金された

### ISSUE THREAD

**Issue by tomotomo9696** [namuyan/nem-tip-bot-bug-report#3]
おそらくの対象ツイート
https://twitter.com/tomotomo_9696/status/902927084330221572
8/31 1:12

出金トランザクション
8/31 1:37:18
アドレス : TB4LP4-4OYD3Q-DMNOHD-GKFRAW-UVBU5Q-J35EPM-KPTU
TXhash : 4ca28eaf1dc5f9373f4f44e14475c4ececb4b71d5243c53dbb320bfd29dc2e44

送金不可のmosaicの出金ツイートをしたところ、
どうやら残高が減らないまま同額のxemで払い出されました。

しかし、このツイートの直後絵文字によるbotの停止があったようで、
出金まで25分もの間が空いており、さらに現在では同じツイートをしても再現しません。
一応ご報告しておきます。

twitter tomotomo_9696
nem address NAUFIPHWAAFJWLE5C33WW36SI5BVDV32ODLFDFBK

**Comment by namuyan** [comment]
バグ報告有難うございます。
昨日から今日の朝にかけて修正しました。
300XEM送金します。
