### ISSUE TITLE
websocket APIからcmd"account/throw"でtextに半角スペースを入れるとエラーになる

### ISSUE THREAD

**Issue by ocknamo** [namuyan/nem-tip-bot-bug-report#4]
websocket APIからcmd"account/throw"でtextに半角スペースを入れるとエラーになって送金できない。

リクエスト
account/throw
送信データ
{
   "sender": "@ocknamo",
   "recipient": "@nagemona",
   "mosaic": "nem:xem",
   "amount": 100000,
   "text": "oyasumi @nagemona",
   "announce": true
}

エラーメッセージ
"'NoneType' object is not subscriptable"

**Comment by namuyan** [comment]
有難うございます。
後ほど100XEMを送りますね。
