### ISSUE TITLE
連続して同様のtipコマンドを行うと認識されない

### ISSUE THREAD

**Issue by fmhk23** [namuyan/nem-tip-bot-bug-report#5]
https://twitter.com/heiuchi23/status/914391613442592768
https://twitter.com/heiuchi23/status/914396364603236352

連続でtipコマンドを行うと、チップ受け渡しができないケースがあります。
（上記URLが該当ツイートです。2回発生し、再現性がある可能性が高いため報告します。）
まったく同様のコマンドを複数人(1~2分で3人程度)に発行したところ、tipbotからの応答がなく、投げ銭も実行されません。
時間をおいて再度ツイートをすると問題なくできました。

ツイッターのリプライの制限の仕様で@tipnemにリプライが認識されていない可能性が高いですが、
- 数分間の数ツイートで制限にかかるような例が調べても見当たらない
- 投げ銭が成立していないが送付先の相手にはリプライが届いているためややこしい
ため報告します。

**Comment by fmhk23** [comment]
twitter: @heiuchi23

**Comment by namuyan** [comment]
こんにちは、
バグ報告有難うございます。Tipnem内部では有効なツイートはいったん貯められ処理層に送られます。
この場合は制限されたのではなくmyheartの定義を取得する段階でエラーが起きてしまったようです。
処理の段階でエラーが起きた場合はロールバックされDBに変化は起きません。

この問題は既に直ったと思ったのですが、まだ解決していないようです。
100XEM相当のバグですので解決を確認しましたらTipnemより投げます。

**Comment by namuyan** [comment]
いろいろ弄っている内に直ってしまったのか投げ銭がうまくいかない事象が現れなくなりました。
クローズさせてもらいます。
後ほどお礼のXEMを送らせてもらいます。
